---
new_page_extension: html
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5e150bb6147f0f0019bb42fb/webhook/forestry
sections:
- type: heading
  label: Heading
- type: document
  path: _config.yml
  label: Config
  templates:
  - config
- type: document
  path: _data/footer.yml
  label: Footer Configuration
  templates:
  - footer
- type: document
  path: index.md
  label: Home
  templates:
  - home
- type: directory
  path: ''
  label: Page
  create: all
  match: "**/*.md"
  exclude: "{_posts/**,README.md,LICENSE.md,index.md,elements.md}"
  templates:
  - page
- type: jekyll-posts
  label: Post
  create: all
  templates:
  - post
- type: document
  path: elements.md
  label: Elements
  templates:
  - elements
- type: document
  path: _data/menus.yml
  label: Site Menus
  templates:
  - site_menus
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
